### ISSUE TITLE
Time information "date_to" in search API is not correct (It seems that time zone of PC is not considered)

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#1]
@EricBourque 
Test Version: 0.9.2 (Second release of V0.9.2)

In case of following screen capture,

End time on GUI is "25.03.2022 08:00:00".
Time zone setting of Windows OS is +9:00
Current local time is 14:59
 
![image](https://user-images.githubusercontent.com/102282918/159861976-6ef2118e-fae7-4e66-8867-6f1a33d0e55d.png)

Expected time for "date_to" that should be used for API is "2022-03-24  23:00:00"  (UTC time of that on GUI)
Current implementation : "2022-03-24 01:58:19" . I estimate that the time is (current time - 13)

**Comment by EricBourque** [comment]
I think we fixed this, the date/time selection was not workig properly. Please let me know if it is ok in v0.9.3

**Comment by Yoshitaka-Fukushima** [comment]
This has been fixed at v0.9.3.
