### ISSUE TITLE
Could you delete "Server_id=9999" on camera selection ?

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#10]
@EricBourque 
Could you delete ?
This is no meaning for user.

![image](https://user-images.githubusercontent.com/102282918/163519384-1d1ce774-c651-41ec-b36e-0618ae798615.png)

**Comment by EricBourque** [comment]
Fixed in v0.9.5: we have hidden the server checkbox
