### ISSUE TITLE
OCR and Container watchlist access permission does not work

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#100]
Test version : v1.9.0 on XProtect 2024R1

Configuration example: Only face watchlist is allowed

![image](https://github.com/user-attachments/assets/634f1e21-d5b2-4a63-b735-0226492b8daa)

Face watchlist is allowed: OK
![{7B5D79A4-2145-4425-B1F8-5B161B5D86C7}](https://github.com/user-attachments/assets/4553659d-0974-4ebe-8043-333e06c03a77)

People, Vehicle, LPR watchlist is not allowed : OK
![image](https://github.com/user-attachments/assets/406650f5-acdc-4913-9c17-53ef7396e7d2)

OCR and Container watchlist is allowed : not OK.
![image](https://github.com/user-attachments/assets/9bd20e55-2eba-4c35-9f87-98be4a0ff749)

![image](https://github.com/user-attachments/assets/4ef67df9-ecbe-4ab4-9b19-c13326983ac0)

@EricBourque  @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Solved for v.1.9.1

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v1.9.1
