### ISSUE TITLE
Error message is shown when we configure on [Roles]-[i-PRO Plugins]-[ORBNET Tools Config Node]

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#101]
Test version: v1.9.0 on XProtect 2024R1

When checking new Roles setting from [i-PRO Plug-in]tab- [ORBNET Tools Config Node],

![image](https://github.com/user-attachments/assets/234083da-86a5-4244-8228-fc689e8c23ce)

error is shown.

![image](https://github.com/user-attachments/assets/987acf0e-7333-4311-9381-0710af83717c)

I do not the ideal behavior, but it is better to be the same as existing Roles options.

@EricBourque  @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
I've noticed this node, "ORBNET Tools Config Node" that should not be there..

![image](https://github.com/user-attachments/assets/d76e48cc-5a2f-44a4-8688-260a2e9a86d8)

**Comment by alexnaicuorbnet** [comment]
I believe this happens only when the plugin is installed after a pre-OSS version has been uninstalled.

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Does "Pre-OSS version" mean official version 1.8? If so, many user will do so. Uninstall v1.8 and install new version.

**Comment by alexnaicuorbnet** [comment]
Pre-OSS version = 1.5.2 (the version that was not using the OSS dll)
That "ORBNET Tools Config Node" is a name that was used in v1.5.2. After switching to OSS dll it was renamed to "i-PRO Active Guard".

**Comment by Yoshitaka-Fukushima** [comment]
We tested again and no.
This happens when new installation and also happens when updating from v1.8.1 to this beta version
@alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Could you share a screenshot of this area when a new installation is made?
![image](https://github.com/user-attachments/assets/76f8bba3-a41f-4f10-bb02-c3da5c91b349)
@Yoshitaka-Fukushima

**Comment by alexnaicuorbnet** [comment]
Could you please re-enable the TeamViewer connection?
@Yoshitaka-Fukushima

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
For our further testing, I would like to know the relationship between the selection status of the following checkboxes for watchlist access and the value specified in the OSS I/F.

![{DCBFBAE9-C88D-4B7E-B0B4-5AE9942A2E62}](https://github.com/user-attachments/assets/82e65e19-2f21-4b7f-83fe-d91e3f06fd47)

![{96DFC8CF-7C6A-4010-9874-4AE32490FF57}](https://github.com/user-attachments/assets/5740dd3f-3143-4ced-8aa0-c68f728e0e04)

Unchecked for both Allow and Deny(Default value) : Parameter "AllowxxxWacthlist" is not included? 
Allow : True for "AllowxxxWacthlist"?
Deny : False for "AllowxxxWacthlist"?

**Comment by alexnaicuorbnet** [comment]
@Yoshitaka-Fukushima 
In the Overall Security tab:
When Allow = checked -> Role has the permission
When Deny = checked -> Role doesn't have the permission
When Allow = unchecked & Deny = unchecked -> Role doesn't have the permission (in this case the user can also go to the i-PRO Plugins security tab and select the permission from there)

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Default status for all check boxes that we added this time are unchecked in i-PRO plug-in tab. 
If my understanding is correct, when user update plug-in from v1.8 to v2.0, user cannot suddenly access watchlist and no attribute is shown in people/vehicle/LPR filter. Could you change default value to be checked ?

The situation is the same as what you did in v1.7 development when roles configurations were added first time.

**Comment by alexnaicuorbnet** [comment]
@Yoshitaka-Fukushima 
Yes, that is the situation at the moment.
I'll what can be done.

**Comment by alexnaicuorbnet** [comment]
Fixed for v.1.9.4
All the new permissions are now set on "Allow" for all existing roles when opening the Management Client after the plugin install.
Changes can be made if another configuration is preferred.

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v1.9.4
