### ISSUE TITLE
New and installed software version information is not shown on Management client

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#102]
Test version: v1.9.0 on XProtect 2024R1

Both server PC and client PC have internet connection.

**Smart client shows the information as expected.**

![image](https://github.com/user-attachments/assets/4947370a-deb2-43b2-bb29-575124620838)

**But Management client shows nothing.**
![image](https://github.com/user-attachments/assets/598fe779-3192-487b-8b78-e438eb36b2c9)

**Our requirement**
![image](https://github.com/user-attachments/assets/b46a0083-684c-4cbd-8e19-1660a5ea99ed)

@EricBourque  @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
I found that this happens when event server is offline or after reloading the plugin node.

**Comment by alexnaicuorbnet** [comment]
Should work for v1.9.1 except sometimes when reloading the plugin node.

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Test version: v1.9.1
Test result: not OK

Installed version is not shown.

![image](https://github.com/user-attachments/assets/4956581b-1308-45d8-b5f5-bc04e83f99c5)

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
We also found that i-PRO Active Guard server's newer version is not shown on Management client.

**Comment by alexnaicuorbnet** [comment]
Is there a newer version than 2.0.0.17? 
@Yoshitaka-Fukushima

**Comment by Yoshitaka-Fukushima** [comment]
No, but we change the version information on dummy URL  ttps://www.psn-web.net/ssbu-t/**temp**/ActiveGuard/LatestVersion.xml so that we can test this feature. 
You can also test it by editing text file "URLCheckLatestVersion.txt".

@alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Solved for  v1.9.2

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v1.9.2
