### ISSUE TITLE
The word "Color" is better than "Colour" in Roles configuration

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#103]
Test version : v.1.9.0 on Xprotect 2024R1

![image](https://github.com/user-attachments/assets/1c3ea81b-0a21-426e-b0de-0f940e619dcd)

Could you change the word from "colour" to "color"?

@alexnaicuorbnet  @EricBourque

**Comment by alexnaicuorbnet** [comment]
Solved for v.1.9.1

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v1.9.1.
