### ISSUE TITLE
It takes about 2 minutes to get LPR and OCR watchlist

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#104]
Test version: v1.9.1 on XProtect 2024R1

Test condition: 
LPR and OCR Genesis app exist in the system. (Not tested for other conditions) 
Watchilst registration is no need.

Phenomenon: 
When opening watchlist configuration UI, it takes about 2 minutes to get configuration data and UI becomes active.

![image](https://github.com/user-attachments/assets/3eb81ae5-daae-4885-92f7-06ede1ff45ef)

*No issue when we use sample application.

 
According to wireshark packet, Active Guard server does receives lpr and OCR releated HTTP request from plug-in in first and second sequence.

![image](https://github.com/user-attachments/assets/2049a87b-bc6b-4f4f-bf4a-fc05be27ee94)

1 minute after,  LPR and OCR related API appeared.

@alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
There is a lag when opening the Watchlist setup window with People app installed as well.
I believe this was also happening on the previous version.

**Comment by Yoshitaka-Fukushima** [comment]
No, we checked again in v1.8.1.
When people and LPR app exist in the system, it takes only 2 seconds to get watchlist.
I attached the packet.

[1.8.1.zip](https://github.com/user-attachments/files/17300572/1.8.1.zip)

@alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Solved for v1.9.3 (I've noticed when accessing OCR Watchlist tab is accessed some calls are made to GetLPRGroup api endpoint, while LPR app is not installedon the camera)

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v1.9.3.
