### ISSUE TITLE
Cannot register second Active Guard server(exception error)

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#106]
Test version: v1.9.1 on XProtect 2024R1

![image](https://github.com/user-attachments/assets/764be933-2afb-4149-a45d-97214954e276)

[Detail.txt](https://github.com/user-attachments/files/17300456/Detail.txt)

IP, port, username and password are blank because we can input after clicking "Add server" button.

@alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Solved for v1.9.2

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v1.9.2
