### ISSUE TITLE
Roles configuration "Attribute: Face\Gender" and "Attribute: Face\Age" does not work  

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#108]
**Test version**
plug-in v2.0.0 as of 29th Oct.

**Phenomenon**
When these two roles are disabled,
![image](https://github.com/user-attachments/assets/78c6cc03-c63b-4b26-ad0f-f2156e167788)

**Expected work on face watchlist window (sample application)**

![image](https://github.com/user-attachments/assets/a5266f4b-777c-4040-8ff2-2e3b05e24c00)

**Current** 
![image](https://github.com/user-attachments/assets/f54c8646-6d0f-4587-88a5-aad6a78b2f87)

**Question**
There is corresponding parameter "AvailableFaceAttribures" in SetCurrentUser I/F.

![{3F5EDAD3-3B5A-4087-8909-345A90CB068B}](https://github.com/user-attachments/assets/f67443ad-ca51-41e4-b688-121d744a2d5d)

When both age and gender is disabled, which do you set?
(i)Parameter "AvailableFaceAttribures" itself does not exist
(ii)Parameter "AvailableFaceAttribures" exists but blank ("gender" and "age" are not set).

I am checking OSS side behavior in parallel.

@alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
For AvailablePeopleAttributes, AvailableFaceAttributes, AvailableVehicleAttributes, and AvailableLPRAttributes
I'm setting null when no attribute permission is set, so it's the (i) option.

@Yoshitaka-Fukushima

**Comment by alexnaicuorbnet** [comment]
I tried with option (ii), setting an empty list instead of null, and it seems that the attributes are hidden as expected.
@Yoshitaka-Fukushima

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
We checked and OSS implementation is correct.

Could you change to be (ii)?
>Parameter "AvailableFaceAttribures" exists but blank ("gender" and "age" are not set).

And please implement the same logic also for  AvailablePeopleAttributes, AvailableVehicleAttributes, and AvailableLPRAttributes.

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v2.0.1
