### ISSUE TITLE
Image are not shown in "Region of interest" filter in some test environment

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#109]
Test version : plug-in 2.0.0 as of 29th Oct.

**Phenomenon**

Following error is shown.

![image](https://github.com/user-attachments/assets/617a8244-8ffc-4e0a-8508-4d794c3d7d02)

**Question**
Is it possible to add any logs when you receive callback about Region of interest and get snapshot via VMS SDK?
We will try to add logs on OSS side to study more.

@alexnaicuorbnet

**Comment by Yoshitaka-Fukushima** [comment]
Test version : plug-in 2.0.0 as of 29th Oct.

**Phenomenon**

Following error is shown.

![image](https://github.com/user-attachments/assets/617a8244-8ffc-4e0a-8508-4d794c3d7d02)

**Question**
Is it possible to add any logs when you receive callback about Region of interest and get snapshot via VMS SDK?
We will try to add logs on OSS side to study more.

@alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
If this is happening for a user that is not in Administrator role make sure its role has the next Overall Security tab permissions:
Management Server: Connect & Read
Cameras: Read & Playback


Not related to this, I've noticed that the callback for Region of interest is only triggered when the checkbox text is clicked, not when the checkbox itself is cliked.
![image](https://github.com/user-attachments/assets/e655d9e7-4378-429f-9003-69611db63741)

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Thank you for your comment.
We did in Administrator and understand the callback trigger.

**Comment by alexnaicuorbnet** [comment]
I've added more logging in v2.0.1

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Could you release when you add log for this ticket? It is OK another ticket remains.

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
I applied v2.0.1 but no logs.
Is log folder "C:\ProgramData\i-PRO\ActiveGuard\SmartClient\Logs" that OSS use ?

**Comment by alexnaicuorbnet** [comment]
The log folder is C:\Users\[userfolder]\AppData\Local\ActiveGuard\SmartClient\Logs
@Yoshitaka-Fukushima

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Thank you. We found this is our test environment issue thanks to your log.
