### ISSUE TITLE
Only available filter is shown on GUI according to the response of "/ai/system/info"

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#11]
Currently, always face, people and vehicle filter is shown even if no camera with the application does not exist in the system.

![image](https://user-images.githubusercontent.com/102282918/163519870-421d704c-fb94-4b31-8670-e2d35520bf42.png)

To help users understand which features are available on the system, it is better that only available filter is shown.
For example, when the camera with AI People detection exist  and the camera with AI Face/Vehicle detection does not exist in the system, only People filter is shown on GUI.

To realize this,
So plugin need to send  "/ai/system/info" to AI server when starting plugin and refer "bestshot_type_list".

![image](https://user-images.githubusercontent.com/102282918/163519841-9eecec34-8ee3-48e0-bde0-c643323ff3ad.png)

**Comment by EricBourque** [comment]
Fixed in v0.9.5
