### ISSUE TITLE
"Clear" button and "Cancel" button does not work

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#12]
@EricBourque 
Test version: v0.9.3

![image](https://user-images.githubusercontent.com/102282918/163520020-b48f2f1b-d21a-4301-a515-49d7e515a78c.png)

When "Clear" is clicked, selected search condition shouldl be default except for "date and time" and "camera".
Currently , search result pane is cleared.

When "Cancel" is clicked while searching, "/ai/v1.0/search/{search_session_id}/cancel" should be sent to AI server.

**Comment by Yoshitaka-Fukushima** [comment]
Sorry for late. 

Could you send cancel API with existing search session in following case ?
-when user closes the tab or Smart client
-when user click "Search"(this means not Lord more but new search) 

Search session will be closed when timeout on server side, but cancel API for unnecessary session is recommended.

**Comment by EricBourque** [comment]
Fixed in 0.9.6. Please let me know if the behavior is how you expect.

**Comment by Yoshitaka-Fukushima** [comment]
I test using V0.9.6 and reconfirm our current system design.
Sorry, I wrote some wrong content.

Cancel API need to be sent to server only when user click "Cancel" button. It is no need to send when closing tab or Smart client. (current implementation works so as long as I confirm. )

Is it possible to do the following regarding the period when the cancel button is displayed?

Cancel button is shown during search for 1st 100 search result and when finished, change to "Search" button automatically.

[AGDRec_20220426_114157.zip](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/files/8559365/AGDRec_20220426_114157.zip)

**Comment by EricBourque** [comment]
Ok, I removed the cancel api when tabs and Smart Client is closed. 
The Cancel button will now automotically go back to "Search" if the search is completed, the search has 0 search results, the search has reached 100 results or if the user clicks "Cancel".

**Comment by mrdx-orb** [comment]
My user impression of the clear button is it would clear both the filter settings and the results onscreen. Providing a blank, default screen once pressed.

**Comment by Yoshitaka-Fukushima** [comment]
Thanks to comment. I also think the clear button behavior you say is OK for user.

**Comment by Yoshitaka-Fukushima** [comment]
Test result in V0.9.7 as of 13th May.

Clear button: OK

Cancel button; not OK (Cancel API is not sent to AI server when clicking cancel while searching )

**Comment by Yoshitaka-Fukushima** [comment]
The procedure is the same. I will confirm again using V0.9.7 as of 17th May.

**Comment by Yoshitaka-Fukushima** [comment]
Test result OK in V1.0.0 release on 18th May.
