### ISSUE TITLE
Sort option does not work

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#14]
@EricBourque 
Test version: v0.9.3

When Ascending is selected,

{"sort_item":"shot-date-time","asc_desc":"desc"} is send

not "sort_item" but "sort-item" is correct,
not "asc_desc"  but "asc-desc"  is correct.

When "Only high relevance" is selected,

please send 
{"sort-item":"similarity","asc-desc":"desc"} .

**Comment by EricBourque** [comment]
Fixed in 0.9.4
