### ISSUE TITLE
Could you show not camera model but camera name for information ?

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#15]
@EricBourque 
Test version: v0.9.3

![image](https://user-images.githubusercontent.com/102282918/163523306-bc3918ca-5acf-417e-b0f7-7dce22375b7f.png)

Currently, "http://192.168.0.57/-Panasonic WV-S1536L" is shown for information.
(This is just the default camera name in case of Video insight.)

It is better to show camera name. Could you show camera name get by XProtect ?
In this screen capture example, "Panasonic WV-S1536L(192.168.0.57) - カメラ 1" is the default camera name on XProtect , I think

**Comment by EricBourque** [comment]
Fixed in 0.9.4
