### ISSUE TITLE
The word shown for selected People or Vehicle feature need to be improved. 

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#16]
@EricBourque 
Test version: v0.9.3

Currently
![image](https://user-images.githubusercontent.com/102282918/163523893-789e61eb-13a6-46b4-a446-20e0115f087d.png)

For example, "yes" is shown. I estimate this is the string for API request.

Could you improve the word so that user can understand.

These are the example in case of VI.
![image](https://user-images.githubusercontent.com/102282918/163523981-711b3946-4651-4521-b785-ea6bc64b0e74.png)

![image](https://user-images.githubusercontent.com/102282918/163524038-95e1581f-955d-4d67-8a8c-85d97ebdf83d.png)

**Comment by EricBourque** [comment]
Fixed in v0.9.5

**Comment by Yoshitaka-Fukushima** [comment]
Tested version: v0.9.5

Almost OK. 
Only when selecting moving direction in People filter,
"No Beard" is shown.

![image](https://user-images.githubusercontent.com/102282918/164693079-8837e7e3-a6d4-485c-a8f6-c52e0dbdc619.png)

**Comment by Yoshitaka-Fukushima** [comment]
I am not sure how to reopen this ticket.

**Comment by EricBourque** [comment]
Sorry, I will let you decide when to close them from now on.

**Comment by EricBourque** [comment]
Fixed in 0.9.6

**Comment by Yoshitaka-Fukushima** [comment]
Moving direction has been modified.

We are sorry we couldn't detect it in the previous test,
words for "Hair type", "Top type" and "Buttom type" are need to be improved.

**Currently, all "Long" or "Short"**

![image](https://user-images.githubusercontent.com/102282918/165200667-a4ca5fe2-196c-49cf-9171-fa380ecc4e2c.png)


**Expected**

![image](https://user-images.githubusercontent.com/102282918/165200771-0b12643f-85f3-4c05-9c1f-c252891e262e.png)

**Comment by EricBourque** [comment]
No problem, fixed in 0.9.7

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in 0.9.7
