### ISSUE TITLE
Delete feature to upload picture for face registration

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#17]
@EricBourque 
To support this feature face detection from still image on client side is required and I think the priority is not high.
So we want to delete this upload feature.

For face registration  window, upload button to add picture should be deleted.

![image](https://user-images.githubusercontent.com/102282918/163588074-e261b7b1-0185-4cba-a884-b40aaab1f88f.png)

"New Registration" button from "Setup Watchlists" should also be deleted.
As a result, only Change and delete watchlist can be done from "Setup Watchlists"

![image](https://user-images.githubusercontent.com/102282918/163588459-c5994630-929d-4461-8fe5-32bba02afc2b.png)

**Comment by EricBourque** [comment]
Fixed for 0.9.4

**Comment by EricBourque** [comment]
Re-open to re-add face upload
