### ISSUE TITLE
"Find camera by features" does not work

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#19]
@EricBourque 
Test version : V0.9.5

Do you plan to implemented in later version ?
Or do I need to explain the specification at first ?

![image](https://user-images.githubusercontent.com/102282918/164697702-40de485e-9cc8-4278-bf30-d357f93fdb47.png)

**Comment by EricBourque** [comment]
I think I fixed it, please try in 0.9.6

**Comment by Yoshitaka-Fukushima** [comment]
Selecting face camera seems OK but people and vehicle camera are not selected when checking "People" and "Vehicle", respectively.

**Comment by EricBourque** [comment]
I don't have people and vehicle anymore, could I please remote connect to your system to debug?

**Comment by Yoshitaka-Fukushima** [comment]
Yes, I will prepare teamviewer connection tomorrow.

There are 4 cameras.
Response of cameras/info is as follows.


{"status_body":{"status":true,"details":[{"srv_id":"9999","code":"00000","message":"OK"}]},"result_body":{"system_type_list":[{"system_type":"multi-AI","srv_id_list":[{"srv_id":"9999","cameras":[{"camera_id":"0080450D0013","camera_ip":"192.168.0.32","camera_model":"WV-S1136","camera_name":"S1136 PeopleDemo","http_port":"80","https_port":"443","communication_mode":"http","meta_protocol":"RTP over RTSP over HTTP","user_name":"admin","**ai_capability":["people","sound"]**,"vms_server_id":"0080450D0013","is_enabled":"true"},{"camera_id":"D42DC5138029","camera_ip":"192.168.0.31","camera_model":"WV-S2136L","camera_name":"S2136L VehicleDemo","http_port":"80","https_port":"443","communication_mode":"http","meta_protocol":"RTP over RTSP over HTTP","user_name":"admin","**ai_capability":["vehicle","sound","aivmd"**],"vms_server_id":"D42DC5138029","is_enabled":"true"},{"camera_id":"D42DC513802E","camera_ip":"192.168.0.33","camera_model":"WV-S2136L","camera_name":"S2136L Face","http_port":"80","https_port":"443","communication_mode":"http","meta_protocol":"RTP over RTSP over HTTP","user_name":"admin","**ai_capability":["face","sound"]**,"vms_server_id":"D42DC513802E","is_enabled":"true"},{"camera_id":"D42DC513803E","camera_ip":"192.168.0.30","camera_model":"WV-S2136L","camera_name":"S2136L PeopleDemo","http_port":"80","https_port":"443","communication_mode":"http","meta_protocol":"RTP over RTSP over HTTP","user_name":"admin","**ai_capability":["people","sound"]**,"vms_server_id":"D42DC513803E","is_enabled":"true"}]}]}]}}

**Comment by EricBourque** [comment]
Ok, thank you.

Kind Regards<fax:Kind%20Regards>
***@***.***
***@***.***
Eric Bourque​​
Director, Chief Software Architect
t:
+41795155526<tel:+41795155526>
 |
m:
+447904345116<tel:+447904345116>
e:
***@***.******@***.***>
 |
w:
orbnetsys.com<https://orbnetsys.com/>
a:
17 Havelock Rd ,  Hastings , TN34 1BP  (UK)
***@***.***<https://www.linkedin.com/company/orbnet-systems>
***@***.***<https://www.youtube.com/channel/UCyaM_CrF8TN8bW0BkQ-V4FA>
***@***.***<https://twitter.com/orbnet_systems>
***@***.******@***.***,0.5785027,15z/data=!4m2!3m1!1s0x0:0x5e042c00a9866584?sa=X&ved=2ahUKEwiIzNrngPzzAhVE-6QKHfL9B14Q_BJ6BAhJEAU>
***@***.***<https://orbnetsys.com/>
***@***.***
***@***.***

​This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of ORBNET Systems. If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone. Please contact the sender if you believe you have received this email in error.
​

**Comment by EricBourque** [comment]
Ok, since I switched to People I got it working. It was only de-selecting, not selecting. Fixed in 0.9.7

**Comment by Yoshitaka-Fukushima** [comment]
Test result OK in V0.9.7 as of 13th, May.
