### ISSUE TITLE
Saved filter cannot be deleted by right click

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#20]
Test version: V0.9.5

Sorry if you do not know about this.
It need the way for user to delete saved filter.

Could you add delete menu by right click like this ?

![image](https://user-images.githubusercontent.com/102282918/164699292-699837b8-7459-48d8-8935-7010167510d9.png)

**Comment by EricBourque** [comment]
Fixed in 0.9.6

**Comment by Yoshitaka-Fukushima** [comment]
thank you. Test result OK
