### ISSUE TITLE
Some minor GUI improvement for V0.9.5

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#21]
Test version: V0.9.5

1. Sunglasse**s** and No Sunglasse**s** are correct.

![image](https://user-images.githubusercontent.com/102282918/164699534-04def927-2e1e-444c-a45e-87de26f2202b.png)

2. Could you change the word in tab from "Active Guard Recording Search" to "Active Guard Search" ?

![image](https://user-images.githubusercontent.com/102282918/164699724-3ceb14ea-24f3-4b7b-8560-47e5144688bb.png)

3. Could you make the color icon a little bigger so that user can select easily ?
 (in People search filter, Vehicle search filter and People watchlist setup screen)
 
Currently
![image](https://user-images.githubusercontent.com/102282918/164700066-6be613b5-05a0-4ca3-bff6-f06e00183da8.png)

Reference

![image](https://user-images.githubusercontent.com/102282918/164700211-520ff831-416c-4cfb-a1c6-846a51789003.png)

4. Could you hide the filter window when clicking out side filter are for "Cameras", "People" and "Vehicle", respectively
  to make it easier for the user to continue the selection operation ?
  
Currently, close button must be clicked.

![image](https://user-images.githubusercontent.com/102282918/164700859-6561efec-d13c-4edc-b0f0-f40e7d5402b5.png)
![image](https://user-images.githubusercontent.com/102282918/164700889-70cd72b7-c789-4f92-8923-904673563e59.png)
![image](https://user-images.githubusercontent.com/102282918/164700913-1466b805-c85e-4632-9211-832902bea76c.png)

Expected( in term of usability), these window are also closed when clicking out side the area.

**Comment by EricBourque** [comment]
Checkboxes size increased in all panels. Need more time for the auto-close, this is a bit tricky.

**Comment by EricBourque** [comment]
fixed in 0.9.7
