### ISSUE TITLE
Score in "Detected info" sometimes shows 0%

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#26]
Test version : v0.9.7

![image](https://user-images.githubusercontent.com/102282918/165732556-c11c0172-98ae-4d0d-94d2-816a0328dfe0.png)

![image](https://user-images.githubusercontent.com/102282918/165732637-369d3c76-d987-44d8-8e9d-f492a8690936.png)

**Comment by Yoshitaka-Fukushima** [comment]
Wireshark packet
[2269.zip](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/files/8581859/2269.zip)

**Comment by EricBourque** [comment]
Fixed in 0.9.7

**Comment by Yoshitaka-Fukushima** [comment]
Test result OK in V1.0.0 release on 18th May.
