### ISSUE TITLE
Watchlist setup window cannot be open in XProtect 2022 R1 with hotfix when using plug-in V0.9.5 or later

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#27]
Test version: V0.9.5 and v0.9.7
XProtect Version: 2022R1  with hotfix for Smart client.

![image](https://user-images.githubusercontent.com/102282918/165733547-5e2b262e-c7cd-421b-9a0a-1b2ad87a7586.png)

When using V0.9.4 with hotfix for XProtect 2022 R1 Smart client, watchlist setup screen can be open correctly.

I guess the change in the plug-in software influence, but do you have any idea about cause ?

**Comment by EricBourque** [comment]
We need more logs. What does it show if you click on "Show details" in the error?

**Comment by Yoshitaka-Fukushima** [comment]
This is the message when clicking "Show details". @EricBourque 

************** Outer Exception **************
Exception type:System.NullReferenceException
Exception message:Object reference not set to an instance of an object.
Exception source:ActiveGuardMilestonePlugins
Exception Target Site: SetSavedWatchlists
at ActiveGuardMilestonePlugins.Client.SetupWatchlists.SetSavedWatchlists(MatchingListResponse matchingListResult)
at ActiveGuardMilestonePlugins.Client.ActiveGuardSmartClientBackgroundPlugin.g.A()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

************** System Info **************
Date and time:	5/9/2022 4:13:29 AM
Machine Name:	ADMIN-PC05-FACE
Processors count:	8
OS version:	Microsoft Windows NT 6.2.9200.0
64 bit OS:	True
64 bit process:	True
IP address:	fe80::f8bd:a309:417c:ebaf%14 (Admin-PC05-Face)
Current user:	Admin-PC05-Face\Admin

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 
This is also happened using V0.9.7 released on 13th May.

************** Outer Exception **************
Exception type:System.NullReferenceException
Exception message:Object reference not set to an instance of an object.
Exception source:ActiveGuardMilestonePlugins
Exception Target Site: SetSavedWatchlists
   at ActiveGuardMilestonePlugins.Client.SetupWatchlists.SetSavedWatchlists(MatchingListResponse matchingListResult)
   at ActiveGuardMilestonePlugins.Client.ActiveGuardSmartClientBackgroundPlugin.g.A()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

************** System Info **************
Date and time:	5/13/2022 4:19:34 AM
Machine Name:	ADMIN-PC05-FACE
Processors count:	8
OS version:	Microsoft Windows NT 6.2.9200.0
64 bit OS:	True
64 bit process:	True
IP address:	fe80::f8bd:a309:417c:ebaf%14 (Admin-PC05-Face)
Current user:	Admin-PC05-Face\Admin

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 
I have just upgraded one our test environment from 2021R2 to 2022R1 and this PC does not reproduce this issue.

We have two test PC and now both 2022R1.

One of the difference is whether we install hotfix for Smart client or not.
The PC without hotfix : not reproduced. I want you to use for verification process.
The PC with hotfix : reproduced.

I am not sure hotfix has relation to root cause or not, try to continue to investigate the cause in terms of environment.

**Comment by Yoshitaka-Fukushima** [comment]
We have performed the following steps on the PC where the problem occurs, but the phenomenon still occurs. I think it depends on the environment other than hotfix.

1. Uninstall XProtect Smart client 2022R1
2. Install XProtect Smart client 2022R1 again.

**Comment by EricBourque** [comment]
> etSavedWatchlists

Can we please have remote access to that machine to try and debug it?

**Comment by EricBourque** [comment]
Error was caused when no matchlists existed in the Active Guard Server. We were enumerating over a null/empty list.
Fixed in 1.0.0
