### ISSUE TITLE
Is it possible to change the default value of the video playback start time to 5 seconds before the image time stamp ?

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#29]
@EricBourque 
Test version: v0.9.7

Currently , it seems that video playback start time is exactly the same with timestamp of the selected thumbnail.

In this case, if the person or car deviates from the camera angle immediately after that time, the person or car will often not be found　in the video.

![image](https://user-images.githubusercontent.com/102282918/167963261-2a03063e-dda0-400b-8a4b-dbc591cfcbd2.png)

Is it possible to change the default value of the video playback start time to 5 seconds before the image time stamp ?
5 seconds is also the default value for our own system.

**Comment by EricBourque** [comment]
fixed in 0.9.7

**Comment by Yoshitaka-Fukushima** [comment]
Test result Ok in V0.9.7 as of 13th May.
