### ISSUE TITLE
Save filter "Include selected camera" does not work

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#30]
@EricBourque 

Test version : v1.0.0 released on 18th May.
This is minor issue.

When select one of two people camera, and save filter with "Include selected camera".

![image](https://user-images.githubusercontent.com/102282918/169482752-19e662db-cb0d-4cb6-86b8-599e94110040.png)

When restored,
Current  result 

![image](https://user-images.githubusercontent.com/102282918/169482905-77598e66-4cbc-4622-95ee-4572b0a00800.png)

 Expected

One camera is selected.

**Comment by EricBourque** [comment]
Fixed in new v1.0.0

**Comment by Yoshitaka-Fukushima** [comment]
Test result OK in V1.0.0 released on 27th May.
