### ISSUE TITLE
Plugin does not show camera when AI server respond GUID as camera ID

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#31]
@EricBourque 
This has relation to #23 ,
Test version : V1.0.0 released on 23th May.

AI server that we are developing responds GUID that XProtect assigned to camera for "ai/v1.0/cameras/info".

![image](https://user-images.githubusercontent.com/102282918/170007367-19297a12-4cba-448c-9b39-8a913107d67b.png)

Plugin does not show the camera.
![image](https://user-images.githubusercontent.com/102282918/170007499-ac8a2ab8-1f8b-4f13-925f-083c6cb1d33c.png)

As long as we confirm the camera ID via XProtect REST API(/api/rest/v1/cameras),
AI server respond correct camera ID.

{
  "array": [
    {
      "displayName": "Panasonic WV-S1536L (192.168.0.57) - カメラ 1",
      "enabled": "True",
      **"id": "81245849-1005-402b-8701-f65074ea5070",**
      "name": "Panasonic WV-S1536L (192.168.0.57) - カメラ 1",
      "channel": 0,
      "description": "",
      "createdDate": "0001-01-01T00:00:00.0000000",
      "lastModified": "2022-04-14T02:37:30.3430000Z",
      "gisPoint": "POINT EMPTY",
      "shortName": "",
      "icon": 0,
      "coverageDirection": "0",
      "coverageDepth": "0",
      "coverageFieldOfView": "0",
      "recordingFramerate": "5",
      "recordKeyframesOnly": "False",
      "recordOnRelatedDevices": "True",
      "recordingEnabled": "True",
      "prebufferEnabled": "True",
      "prebufferInMemory": "True",
      "prebufferSeconds": 3,
      "edgeStorageEnabled": "False",
      "edgeStoragePlaybackEnabled": "False",
      "manualRecordingTimeoutEnabled": "True",
      "manualRecordingTimeoutMinutes": 5,
      "recordingStorage": {
        "type": "storages",
        "id": "673be0ba-6731-44a7-9d6f-2157083fef1c"
      },
      "relations": {
        "parent": {
          "type": "hardware",
          "id": "bf3c1c8f-6396-476d-9d7d-0557ab98c5e3"
        },
        "self": {
          "type": "cameras",
          "id": "81245849-1005-402b-8701-f65074ea5070"
        }
      }
    },
    {
      "displayName": "Panasonic WV-S2136L (192.168.0.52) - カメラ 1",
      "enabled": "True",
      **"id": "b54973f4-1e2b-421b-93ff-db1c72e9c061",**
      "name": "Panasonic WV-S2136L (192.168.0.52) - カメラ 1",
      "channel": 0,
      "description": "",
      "createdDate": "0001-01-01T00:00:00.0000000",
      "lastModified": "2022-04-11T04:13:44.8670000Z",
      "gisPoint": "POINT EMPTY",
      "shortName": "",
      "icon": 0,
      "coverageDirection": "0",
      "coverageDepth": "0",
      "coverageFieldOfView": "0",
      "recordingFramerate": "5",
      "recordKeyframesOnly": "False",
      "recordOnRelatedDevices": "True",
      "recordingEnabled": "True",
      "prebufferEnabled": "True",
      "prebufferInMemory": "True",
      "prebufferSeconds": 3,
      "edgeStorageEnabled": "False",
      "edgeStoragePlaybackEnabled": "False",
      "manualRecordingTimeoutEnabled": "True",
      "manualRecordingTimeoutMinutes": 5,
      "recordingStorage": {
        "type": "storages",
        "id": "673be0ba-6731-44a7-9d6f-2157083fef1c"
      },
      "relations": {
        "parent": {
          "type": "hardware",
          "id": "af6634bf-2bfd-4903-9254-ce7ca7091567"
        },
        "self": {
          "type": "cameras",
          "id": "b54973f4-1e2b-421b-93ff-db1c72e9c061"
        }
      }
    },
    {
      "displayName": "Panasonic WV-S2136L (192.168.0.53) - カメラ 1",
      "enabled": "True",
      **"id": "e6d3d0fa-c6f8-40c6-be2b-81477b0c7af2",**
      "name": "Panasonic WV-S2136L (192.168.0.53) - カメラ 1",
      "channel": 0,
      "description": "",
      "createdDate": "0001-01-01T00:00:00.0000000",
      "lastModified": "2022-04-11T04:13:45.2100000Z",
      "gisPoint": "POINT EMPTY",
      "shortName": "",
      "icon": 0,
      "coverageDirection": "0",
      "coverageDepth": "0",
      "coverageFieldOfView": "0",
      "recordingFramerate": "5",
      "recordKeyframesOnly": "False",
      "recordOnRelatedDevices": "True",
      "recordingEnabled": "True",
      "prebufferEnabled": "True",
      "prebufferInMemory": "True",
      "prebufferSeconds": 3,
      "edgeStorageEnabled": "False",
      "edgeStoragePlaybackEnabled": "False",
      "manualRecordingTimeoutEnabled": "True",
      "manualRecordingTimeoutMinutes": 5,
      "recordingStorage": {
        "type": "storages",
        "id": "673be0ba-6731-44a7-9d6f-2157083fef1c"
      },
      "relations": {
        "parent": {
          "type": "hardware",
          "id": "c38fd255-8336-48c6-9af1-814da29085b1"
        },
        "self": {
          "type": "cameras",
          "id": "e6d3d0fa-c6f8-40c6-be2b-81477b0c7af2"
        }
      }
    },
    {
      "displayName": "Panasonic WV-S2136L (192.168.0.55) - カメラ 1",
      "enabled": "True",
      **"id": "e3a6fa3f-2068-4ba4-acf8-a003eb13c972",**
      "name": "Panasonic WV-S2136L (192.168.0.55) - カメラ 1",
      "channel": 0,
      "description": "",
      "createdDate": "0001-01-01T00:00:00.0000000",
      "lastModified": "2022-04-11T04:13:45.2870000Z",
      "gisPoint": "POINT EMPTY",
      "shortName": "",
      "icon": 0,
      "coverageDirection": "0",
      "coverageDepth": "0",
      "coverageFieldOfView": "0",
      "recordingFramerate": "5",
      "recordKeyframesOnly": "False",
      "recordOnRelatedDevices": "True",
      "recordingEnabled": "True",
      "prebufferEnabled": "True",
      "prebufferInMemory": "True",
      "prebufferSeconds": 3,
      "edgeStorageEnabled": "False",
      "edgeStoragePlaybackEnabled": "False",
      "manualRecordingTimeoutEnabled": "True",
      "manualRecordingTimeoutMinutes": 5,
      "recordingStorage": {
        "type": "storages",
        "id": "673be0ba-6731-44a7-9d6f-2157083fef1c"
      },
      "relations": {
        "parent": {
          "type": "hardware",
          "id": "667e3564-8f35-4782-8368-6d8b7e9094ae"
        },
        "self": {
          "type": "cameras",
          "id": "e3a6fa3f-2068-4ba4-acf8-a003eb13c972"
        }
      }
    }
  ]
}

**Comment by EricBourque** [comment]
Fixed in new v1.0.0

**Comment by Yoshitaka-Fukushima** [comment]
Test result OK in V1.0.0 released on 27th May.
