### ISSUE TITLE
Attribute shown in people registration from Actions is not correct

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#32]
@EricBourque 
Test version : v1.0.0 released on 27th May.

**1. Attribute information shown on GUI is not matched with those in "detected info".**

![image](https://user-images.githubusercontent.com/102282918/171364006-35d5d8da-f3df-45be-ba95-75f36bc6cfd0.png)

**2. About "Camera", currently "0 cameras" are shown**

Expected
It is no need to show Camera on this GUI.
Internally, all camera with People application should be selected.

**3. When click register, API includes 1 camera ID** 

![image](https://user-images.githubusercontent.com/102282918/171365754-5ceafc2e-67fc-4808-99ca-d3642f27ecfe.png)

Expected
Internally, all camera with People application should be selected.

**4. When  I open Setup watchlist,**  and select the watchlist,

"Cameras(0)"  is shown though checked camera exist.

![image](https://user-images.githubusercontent.com/102282918/171366190-9df219f7-6b85-41c9-b490-158fa272c1c3.png)

Cameras(n) is shown.  *n : the number of camera checked

**Comment by Yoshitaka-Fukushima** [comment]
Test version: V1.0.0 released on 17th, August

1. Attribute information shown on GUI is not matched with those in "detected info".
->  Partially fixed. Not all attributes with high score value are not shown.
  
  
![image](https://user-images.githubusercontent.com/102282918/189831449-4be98fa5-58e6-405e-b03e-c29aaddf2a9b.png)
 
-Text in red rectangle are no need in this screen
 
![image](https://user-images.githubusercontent.com/102282918/189831760-c9c29ffc-1f1c-4c98-ba8e-ea1d5cc028cd.png)

-"Sunglasses: None"  and "Mask: Yes" should be shown because these are also high score value of this thumbnail.

3. When click register, API includes 1 camera ID

-> not fixed. Only 1 camera ID is specified in API even if multiple cameras with AI People detection exist.

![image](https://user-images.githubusercontent.com/102282918/189832355-e864bedf-d3b3-4247-b54c-6e4fd575718f.png)

**Comment by EricBourque** [comment]
Fixed in 1.0.1 and added bag, bag color, shoe color

**Comment by Yoshitaka-Fukushima** [comment]
Test version: V1.0.1 released on 10th Oct.
Test result : not OK

![image](https://user-images.githubusercontent.com/102282918/194972632-47231ea1-98cd-448d-bfec-98182f8e952e.png)

Expected work
-People image is shown.
-Vehicle information is no need

**Comment by EricBourque** [comment]
Please test in 1.0.2

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 13th,Jan.
Test result : not OK

Almost OK, but sorry, could you remove "bag", "bag_color" and "shoes_color" in this New people watchlist registration ?

This screen capture is the example for "bag_color".
![image](https://user-images.githubusercontent.com/102282918/212660493-612012f1-eb1d-44e8-96b7-8e2e494b1c02.png)

This is because, as Active Guard server specifications, bag", "bag_color" and "shoes_color" cannot be registered as watchlist.

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 23.01.2023

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.0.3 released on 24th,Jan.
Fixed.
