### ISSUE TITLE
Search parameter for face watchlist

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#35]
@EricBourque
Test version: V1.0.0 released on 27th, May

When ”Arbitrary” is selected for "Gender" in Face watchlist **Search** window (not registration window),

![image](https://user-images.githubusercontent.com/102282918/171526012-03ffabfb-c792-4fb2-ade7-ca23c18d4737.png)

![image](https://user-images.githubusercontent.com/102282918/171526001-52baf40e-714f-4bd7-b312-7cefe80a7eb0.png)

Currently
 **{"op":"and","column":"gender","comp":"equal","value":"unknown"}** exist in API request and the watchlist with male or female are not shown as default.

{"search_type":"list","cond":[**{"op":"and","column":"gender","comp":"equal","value":"unknown"},**{"op":"and","column":"matching_status","comp":"equal","value":"enable"}]}

Expected
{"search_type":"list","cond":[{"op":"and","column":"matching_status","comp":"equal","value":"enable"}]}

user can search all result regardless of the gender selected when registering the face.

**Comment by PetrutVasile** [comment]
Fixed in the new version

**Comment by Yoshitaka-Fukushima** [comment]
Test version: V1.0.0 released on 17th, August

Fixed
