### ISSUE TITLE
Bottom type detected info in people search is not correct

### ISSUE THREAD

**Issue by PetrutVasile** [ORBNETSYS/i-PRO-Active-Guard-Public#38]
The information shown about attribute "Bottom type" in detected info inverts "Short" and "Long".

<img width="1573" alt="bottomtype" src="https://user-images.githubusercontent.com/90925838/173080382-96f4c32b-1da8-44e9-8b8e-82f15bf95a56.PNG">

**Comment by Yoshitaka-Fukushima** [comment]
Test version: V1.0.0 released on 17th, August

Original issues has been fixed but 3 minor issues exist. I will also add comment to Git #38.

1.Not “Recomended Size” but “Recommended Size” is correct.
2. In current version, “N/A” is always shown for Recommended Size.
    AI server respond “recommended”: “yes” or “recommended”: “no”.  Plug-in needs to show this value.

 
![image](https://user-images.githubusercontent.com/102282918/191501038-33a847ae-c88b-4679-9124-698465b2981d.png)



3. The display order of “Short” and “Long” in the Bottom type is reversed.
   It is correct to display Long, Short like the Tops type.
 
![image](https://user-images.githubusercontent.com/102282918/191501048-696e7d8f-41ec-4b67-8c93-ad99e256d00f.png)

**Comment by EricBourque** [comment]
fixed in 1.0.1

**Comment by Yoshitaka-Fukushima** [comment]
Test version: V1.0.1 released on 7th Oct.
Test result : not OK

Some parameters in Detected info tab are not shown correctly.

![image](https://user-images.githubusercontent.com/102282918/195003472-aff4a0bc-5b8b-4c67-a480-94d5bb1800b4.png)

I estimate API response related to "Bag" affected the plugin.
Could you modify to show correctly and also support "Bag", "Bags color" and "Shoes color"  in detected info tab ?

This is the sample screen in our own system.

![image](https://user-images.githubusercontent.com/102282918/195005124-22d9d460-5d0e-4aa7-a02d-f321553734c2.png)

**Comment by EricBourque** [comment]
Fixed in 1.0.2

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.0.3 released on 13th, Jan.
Test result : not OK

Original issue No.2 in this ticket has not been fixed.
>2. In current version, “N/A” is always shown for Recommended Size.

![image](https://user-images.githubusercontent.com/102282918/212657193-2c4ecced-8773-4b50-b7cf-c83e6a237cf2.png)

Could you reopen this ticket ? @EricBourque

**Comment by EricBourque** [comment]
Re-opened to sort out recommended size not being displayed

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 23.01.2023

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 24th,Jan.
Fixed.

Could you close this issue ? It seems I cannot. @EricBourque
