### ISSUE TITLE
The filter page has a different size after minimizing the tab

### ISSUE THREAD

**Issue by PetrutVasile** [ORBNETSYS/i-PRO-Active-Guard-Public#39]
<img width="1572" alt="filterpage" src="https://user-images.githubusercontent.com/90925838/173080704-fee250c1-b2f5-4fad-b8a5-b39bd66ea398.PNG">

**Comment by PetrutVasile** [comment]
Fixed in the new version

**Comment by Yoshitaka-Fukushima** [comment]
Test version : V1.0.0 released on 17th, August.

Fixed.

Could you close this ticket ? Sorry, but I cannot. @PetrutVasile  @EricBourque
