### ISSUE TITLE
Add face image to existing face watchlist (Currently only 1 face image can be registered)

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#41]
@EricBourque 
Test version: V1.0.0 released on 17th, August

As the Active Guard server specification , up to 10 face image for each watchlist can be registered.

**Actions - Face registration - ”2-b. Add to registered face" - Update registration**

![image](https://user-images.githubusercontent.com/102282918/189837666-cc914a7e-64e1-4122-9ef8-b801645a1f88.png)

Current version
-registered information (ex. First name and Last name )are not shown
-Registered face image are not shown. Only selected face is shown.
![image](https://user-images.githubusercontent.com/102282918/189840937-4de6e045-2844-4dcf-aaad-05f2339092e8.png)

Expected work
![image](https://user-images.githubusercontent.com/102282918/189838730-015bde2b-cb4c-465e-9790-840164043901.png)

-registered information (ex. First name and Last name )are shown
-Selected face are shown as 2nd, 3rd ,4th ,,, image for this watchlist.

In terms of API to update watchlist,
"Image_id_list[]" means array, plug-in can send multi-ple face images.
![image](https://user-images.githubusercontent.com/102282918/189840398-149b24bd-d452-4baf-ba61-3625435bcbfc.png)

![image](https://user-images.githubusercontent.com/102282918/189840342-1863cfc0-c4c1-4df6-8f14-bdc91efe038b.png)

"image_representive":"yes" must be used for only one face image.

**Comment by Yoshitaka-Fukushima** [comment]
Test version: V1.0.1 released on 5th Oct.

Currently, when additional face image is registered, additional face image is set for representative image as default.
 
![image](https://user-images.githubusercontent.com/102282918/194222299-87e919d3-9c96-4159-acf0-4dbe9c125d35.png)

Could you keep original representative face image ?

Switch representative face image by right click operation is good feature.

**Comment by EricBourque** [comment]
Fixed in 1.0.2
