### ISSUE TITLE
Some filter option for Bag, Bag color and Shoes color should be shown when "Advanced filter" is clicked.

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#43]
Test version: V1.0.1 released on 5h Oct.

![image](https://user-images.githubusercontent.com/102282918/194216123-2607d97a-e0ea-4e96-b1ff-bc6fa5a2f693.png)

Button to adjust threshold(low, medium, high) and check box for "Exclude selected color" should not be shown as default and should be shown when "Advanced filter" is clicked to be the same policy with another color attributes.

**Comment by EricBourque** [comment]
Fixed in 1.0.1

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in 1.0.1 released on 6th Oct.
