### ISSUE TITLE
Could you support "Clear" face image for face filter ?

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#44]
Test version: V1.0.1 released on 5th, Oct.

Currently, user cannot clear face image for face filter once set.

Could you support "clear" face function by right click as follows ?
![clear](https://user-images.githubusercontent.com/102282918/194218108-4e3e0e52-d023-46fa-ba8a-3c190cb90559.PNG)

**Comment by EricBourque** [comment]
Yes, I will add later. In the meantime you can clear by clearing the filter at the bottom or by clicking clear on the watchlist search I think

**Comment by EricBourque** [comment]
Done in new 1.0.1 release 07.10.2022

**Comment by Yoshitaka-Fukushima** [comment]
Test version: V1.0.1 released on 7th Oct.
Test result : OK
