### ISSUE TITLE
Face image from watchlist cannot be set for face filter

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#46]
Test version : V1.0.1 released on 6th Oct.

When searching face watchlist and clicking face image, the face image will not be set for left side.
![image](https://user-images.githubusercontent.com/102282918/194459154-00d6987a-6df4-4966-a287-777935d8d683.png)

We could in previous version (V1.0.1 released on 4th)

**Comment by EricBourque** [comment]
Sorry about that, I have fixed it and published a new installer. I also added the right-click to clear the face filter

**Comment by Yoshitaka-Fukushima** [comment]
Test version: V1.0.1 released on 10th Oct.
Test result : OK
