### ISSUE TITLE
Start and End time for search API is not correct when unchecked for "Search only within"

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#47]
Test version: V1.0.1 released on 7th Oct.

Start time and End time should be used when unchecked for "Search only within".
In this sample screen, time zone is UTC +9:00.  Not Start and end time on GUI but current time (UTC 03:34:20) when clicking search button is used.

![image](https://user-images.githubusercontent.com/102282918/194991798-d5ec3e6f-8676-44de-89d7-5a626e97739d.png)

**Comment by EricBourque** [comment]
Fixed in 1.0.1

**Comment by Yoshitaka-Fukushima** [comment]
Test version: V1.0.1 released on 11th Oct.
Fixed.
