### ISSUE TITLE
”Category" in face watchlist cannot be registered

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#48]
Test version: V1.0.1 released on 7th, Oct

Category field user input is not used in API, ( "Category": null is sent to server)

  
![image](https://user-images.githubusercontent.com/102282918/195058653-c424c054-54a9-4c12-add0-1913725f131d.png)

**Comment by EricBourque** [comment]
How should the category work exactly? What is the purpose of the 2nd category control? Should we add a list of pre-defined categories?

**Comment by Yoshitaka-Fukushima** [comment]
I upload video.
https://user-images.githubusercontent.com/102282918/196347137-5408ee58-676d-4ae4-9d47-0273baa7a9ac.mp4

Right pull down menu for Category shows existing category. User can select from existing category or input any string for search watchlist and registration.

Existing category list are included in the response of "/ai/system/info". Could you use this ?

![image](https://user-images.githubusercontent.com/102282918/196347832-b0f51f09-666f-48df-a7be-d4c9b6a714fd.png)

**Comment by EricBourque** [comment]
Fixed in 1.0.2
