### ISSUE TITLE
Validity period for People watchlist may be unintentionally specified in API

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#50]
Test version :V 1.0.1

When there is no watchlist registration, default GUI status for "Validity period" is as follows and no problem when clicking "Save".
Request API does not include "expire_date" as expected.

![image](https://user-images.githubusercontent.com/102282918/200550047-c15ddd33-2f36-4dbc-a459-1c16ba4dba07.png)

When I check and uncheck again, GUI status becomes different as follows and has problem when clicking "Save".
Request API includes "expire_date".
![image](https://user-images.githubusercontent.com/102282918/200550346-29301b45-df40-4f3a-89c9-5c407a3bc316.png)

![image](https://user-images.githubusercontent.com/102282918/200550745-a493fddd-23e0-4b42-8d4d-34ea769d4cb5.png)

Situation is the same for new registration and update watchlist.

**Comment by EricBourque** [comment]
Fixed in 1.0.2

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 24th,Jan.
OK for new registration but not OK for updates.

Procedure
1. Create people watchlist A , Validity period is unchecked.
2. Create people watchlist B , Validity period is enabled.
3. Close watchlist setup screen and open again
4. Select watchlist A

Phenomenon
Validity period in watchlist A is checked and date shows that of watchlist B.

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 26.01.2023

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 27th, Jan.
Fixed.
