### ISSUE TITLE
Milestone 2022 - R3 - Active Guard Plugin 1.01 - Face tab

### ISSUE THREAD

**Issue by SirTapp** [ORBNETSYS/i-PRO-Active-Guard-Public#51]
Milestone 2022 R3 -

1. When you select the "face" tab within the Smart Client, the 'upload' photo button does not work
2. Within the Face tab in the Smart Client and you navigate to the "search watchlist' button and then select it, the GUI displays white boxes, not watch list photos or information pertaining

**Comment by alexnaicuorbnet** [comment]
We are working on an update, please give us 1-2 weeks for a new version which will have allot of added functionality.

**Comment by EricBourque** [comment]
Fixed in 1.0.2

**Comment by EricBourque** [comment]
> 2\. tab in the Smart Client and you navigate to the "search watchlist' button and then select it, the GUI displays

Dear "SirTapp",
The new version is imminent, please send us your email if you wish to be notified when the new version will be released.
