### ISSUE TITLE
Filter color for bag color and shoes color with Exclude selected color option is not correct

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#52]
Test version: V1.0.2 released on 6th Jan.

![image](https://user-images.githubusercontent.com/102282918/211522183-3e281f63-c65f-4a5f-bf26-bdacb0391d51.png)

When selecting specific color for Hair, Tops or Bottoms and check exclude selected color, color on left filter is changed. (No problem)

When selecting specific color for Bag or Shoes and check exclude selected color, color on left filter is not changed. (Need to be modify)

**Comment by EricBourque** [comment]
Fixed in 1.0.2

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 13th, Jan.
Fixed.
