### ISSUE TITLE
"middle" is used in API when threshold "High" is selected for People search filter

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#53]
Test version: V1.0.2 released on 6th Jan.

![image](https://user-images.githubusercontent.com/102282918/211524609-c062e723-5a23-4b2f-9ab5-4ae0b0d74e41.png)

![image](https://user-images.githubusercontent.com/102282918/211524693-93178dde-24ce-40ed-882f-7c9741bf1ff6.png)

"xxx_similarity" in API should be matched with GUI.

**Comment by EricBourque** [comment]
Fixed in 1.0.2 released on 10th Jan.

**Comment by Yoshitaka-Fukushima** [comment]
Test version:  v1.0.3 released on 13th, Jan.

Almost OK ,but similarity for hair type and hair color are not correct.
Could you reopen this ticket ? @EricBourque 
 
1. "hair_style_similarity" always use "middle" even if "Low" or "High" is selected in GUI.
![image](https://user-images.githubusercontent.com/102282918/212624506-ed371b98-0dee-4cdb-b0e7-2ff74ea83658.png)

2.  "hair_color_similarity" does not exist in API event if "Low" or "High" is selected in GUI.

**Comment by EricBourque** [comment]
similarity not working for hair type and hair color

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 20.01.2023

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 24th,Jan.
Fixed.
