### ISSUE TITLE
People watchlist cannot be registered from Actions button (no API is sent)

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#57]
Test version :V1.0.2 released on 6th, Jan.

1. When registering people watchlist from Actions button, error message is shown.
   According to wireshark packet, no API is sent to Active Guard server.

2. radio button "Disable matching/Delete registration" should not be shown when unchecked for "Validity period".
   (When I check and uncheck again, these will be hidden, correctly.)

![image](https://user-images.githubusercontent.com/102282918/211968367-588329b9-2381-4c4e-8c08-880657790564.png)

**Comment by alexnaicuorbnet** [comment]
Fix pushed. Can be tested,

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 13th, Jan.
Fixed.
