### ISSUE TITLE
In the Tooltip for Saved filter, Date&time is not shown and bags color text is no need. 

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#59]
Test version: v1.0.2 released on 6th Jan.

**v1.00**
Date&time is shown correclty.

![v1 00](https://user-images.githubusercontent.com/102282918/211973662-76c365af-ac67-47ce-b5d5-3b324bb8c9ee.PNG)

**v1.02**
1.Date&time is not shown.
2.
---
Bag: Bag
Bag: Black Bag ■ 
 ---
should be 
---
Bag: Bag ■ 
 ---
like Top or Bottom.

![image](https://user-images.githubusercontent.com/102282918/211973772-86532440-885c-414d-8f36-f776c3ce87d7.png)

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.0.3 released on 13th, Jan.

1. Date& time : not OK

(i) The same time for Start and End are shown in tooltip.
(ii) not  local time but UTC time is shown in tooltip.

2.Bags color issue : OK

**Comment by alexnaicuorbnet** [comment]
Fixed.

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.0.3 released on 19th, Jan.
Fixed.
