### ISSUE TITLE
API query for "Detected info"

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#6]
**Currently**
Response for "GET /ai/v1.0/thumbnail/search/(session_id)?result-from=1&result-count=100" is shown.
![image](https://user-images.githubusercontent.com/102282918/159909384-b0c85a23-87b5-4e0c-8391-78d106576758.png)

**Expected**
More detail information related is need to be shown
![image](https://user-images.githubusercontent.com/102282918/159909800-6fcec1dd-7db2-4488-b115-ece9737aa287.png)

This information can be get by adding "info=on" like
GET /ai/v1.0/thumbnail?thumbnail-key=xxxxx**&info=on**

so, could you use "GET /ai/v1.0/thumbnail?thumbnail-key=xxxxx**&info=on**" instead of "GET /ai/v1.0/thumbnail?thumbnail-key=xxxxx" ?

**Comment by EricBourque** [comment]
How do we know exactly if:

Person
Vehicle

Do I have to check several fields or is Gender and Vehicle type enough?
Thank you

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 
You can distinguish people or vehicle either the response of "GET /ai/v1.0/thumbnail?thumbnail-key=xxxxx**&info=on**" or 
"GET /ai/v1.0/thumbnail/search/{search_session_id}" before sending that.

From the response of "GET /ai/v1.0/thumbnail?thumbnail-key=xxxxx**&info=on*

In case of people, people attribute information included.

![image](https://user-images.githubusercontent.com/102282918/163586099-6a1d27ad-8449-4efe-bca5-491e7d0712c4.png)

In case of vehicle, vehicle attribute information is included.

![image](https://user-images.githubusercontent.com/102282918/163586215-757407bb-e4ea-4ac2-a367-a4fa6dd363c4.png)


"GET /ai/v1.0/thumbnail/search/{search_session_id}" also show which image is face, people or vehicle.

![image](https://user-images.githubusercontent.com/102282918/163586569-9b869088-fef3-4d67-b484-c00af77de8c7.png)

**Comment by EricBourque** [comment]
fixed in 0.9.6 please let me know if it is OK

**Comment by Yoshitaka-Fukushima** [comment]
Detected info of People, following description may have bug.

Day/Night: yes
Direction: color
Recommended size; middle-left

![image](https://user-images.githubusercontent.com/102282918/165201460-3864ac01-4e80-470f-8e00-fcc5e126badd.png)


Detected info of Vehicle, error is shown
![image](https://user-images.githubusercontent.com/102282918/165201532-3d1403d5-02a7-4ac8-a9cf-de0e16b33d5e.png)

**Comment by EricBourque** [comment]
Fixed in 0.9.7

**Comment by mrdx-orb** [comment]
I have checked this morning with 0.9.7 installed.

Face search show;
<img width="257" alt="image" src="https://user-images.githubusercontent.com/92920127/166660598-96ca4341-7e49-40a8-ba8f-7da6e05687fe.png">

People search show;
![image](https://user-images.githubusercontent.com/92920127/166661067-fb4a0696-c09c-4875-9e4d-0054debde266.png)

Vehicle search shows;
<img width="254" alt="image" src="https://user-images.githubusercontent.com/92920127/166661151-11de7cc2-09d3-4da7-a206-07216063eef7.png">

**Comment by Yoshitaka-Fukushima** [comment]
Test result in V0.9.7 as of 13th May.

**Face : not OK**
![image](https://user-images.githubusercontent.com/102282918/168286671-4b963c84-09f0-4c61-9bfd-acd2b91a6641.png)

Detected size is not shown (but can be suspended to next version because requirement was not clear).
Expected
![image](https://user-images.githubusercontent.com/102282918/168288106-d1645489-299d-4b9e-8bfd-1dfa2ac2e2d7.png)

**People : not OK**
Detected size is not shown as well as Face. It can be suspended to next version.

Expected
![image](https://user-images.githubusercontent.com/102282918/168287891-1939c6c8-3513-4fc4-b30b-863d4bcbda3a.png)

**Vehicle : not OK**
This should be modified.
![image](https://user-images.githubusercontent.com/102282918/168287073-a718f1ca-e862-4d77-8577-a4cb97df0beb.png)

Expected
![image](https://user-images.githubusercontent.com/102282918/168287985-029767fe-dc58-4f92-8b8d-2693213bddd1.png)

**Comment by EricBourque** [comment]
Fixed in new v0.9.7

**Comment by Yoshitaka-Fukushima** [comment]
Test result OK in V1.0.0 released on 18th.
