### ISSUE TITLE
"Filter condition", time and camera name in Exported html file is not correct. 

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#60]
Test version : v1.0.2 released on 6th, Jan.

**Expected**
Filter condition is shown correctly.
Time: not UTC but local time so that user can understand.
Camera name is shown correctly.

![image](https://user-images.githubusercontent.com/102282918/212019758-ea9b34d3-a056-49b4-b300-8e652b7aa567.png)

**Currently**

![image](https://user-images.githubusercontent.com/102282918/212020312-db70f61f-e664-4a77-8b40-5280f662e501.png)

I estimate that it is easy to improve Time and Camera name.
About Filter condition, it is complicated, if it takes much time to modify, I want to delete "Filter condition".

**Comment by alexnaicuorbnet** [comment]
Fix submitted, please test.

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 13th, Jan.

Not OK.
Date&time in filter condition is blank:

![image](https://user-images.githubusercontent.com/102282918/212598185-fdff0197-b136-4746-8ea0-721aac1a8f91.png)

Local time and camer name for each image have been fixed.

**Comment by EricBourque** [comment]
Sorry, this was fixed but you were not able to test because we had not sent a new version yet. From now on, when we update and issue we will add the version and the date so you don't test for nothing.

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 24th, Jan.

Not OK.
Date&time in filter condition show the same time for Start and End.

![image](https://user-images.githubusercontent.com/102282918/214496104-ecf046b6-321a-48d2-b736-80f5ba1cdee3.png)

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 25.01.2023

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 27th, Jan.
Fixed.
