### ISSUE TITLE
[Multiple server registration] Default server name and IP address

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#62]
Test version: v1.0.2 released on 6th,Jan.

**Default server name**

Currently, when "Add Server" is selected, always "AI Server" is shown for "Server Name" as default.
When default name is used, it is difficult for user to distinguish server.

![image](https://user-images.githubusercontent.com/102282918/212042631-bc331da7-f7b6-4451-86ee-1fa45201e2ff.png)

Could you improve default server name as follows ?

i-PRO Active Guard server 1
i-PRO Active Guard server 2
i-PRO Active Guard server 3
...
 

**IP Address**

Currently, the same i-PRO Active Guard server can be registered in duplicate.
![image](https://user-images.githubusercontent.com/102282918/212045948-fed67607-939e-4c29-8553-ff7baa29c51f.png)

Could you prohibit server registration with the same IP address ?

**Comment by alexnaicuorbnet** [comment]
Changed default naming and added validation for unique ip. Can be tested.

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.0.3 released on 19th, Jan.
Fixed.
