### ISSUE TITLE
Face search - Similar face search from Actions should not enable people and vehicle filter

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#63]
Test version: v1.0.2 released on 6th, Jan.

After searching for face images, click Similar Search button.
![image](https://user-images.githubusercontent.com/102282918/212044380-7cda910e-7d4d-47e5-a408-0f67f06858dc.png)

**Expected.**
Only face filter is enabled and only similar face images to the selected face are shown.

**Currently.**
People and Vehicle filter is enabled automatically and many images including people and vehicle are shown.

![image](https://user-images.githubusercontent.com/102282918/212044269-85ad24f7-b858-43e5-8106-e00f2ab54cd8.png)

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 20.01.2023

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 24th,Jan
Fixed.
