### ISSUE TITLE
People search - Similar face search from Actions will show Error dialog

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#64]
Test version: v1.0.2 released 6th on Jan.

Search people with "Recognizable face only" filter.
![image](https://user-images.githubusercontent.com/102282918/212047039-bd8a2d25-2779-4c33-8e6f-d63143c67a58.png)

Then select "Similar face search" in Actions.

![image](https://user-images.githubusercontent.com/102282918/212047600-603a90dd-ade1-4f2f-a5ae-980695d98689.png)

1.Error message is shown (not OK)
2.Face filter will be enabled automatically (OK)
3.People filter remains enable. (Could you disable in this case ?)

**Comment by alexnaicuorbnet** [comment]
To be tested.

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.0.3 released on 24th, Jan.
Not OK (Another related phenomenon occurs)

Procedure
1.Search people with "Recognizable face only" filter and playback
2.Search for similar face
3.Disable face filter and enable people filter and search

Exception error occurs

![image](https://user-images.githubusercontent.com/102282918/214497975-4f38f753-5ae6-466e-b27f-65748e718899.png)

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 25.01.2023
A thing to consider: when doing searches from the Actions menu the filter sections that get disabled also get reset, so any selections on those disable filters get lost. You might want to only have the filter sections disabled.

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 27th,Jan.
Fixed

I understand your point, let us discuss for the future version.
