### ISSUE TITLE
Similar face search - API parameter has typo ”search_tumbnail_1” should be "search_thumbnail_1“

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#65]
Test version : v1.0.2 released on 6th. Jan.

When searching for face using face image, plug-in sends API

Currently

![image](https://user-images.githubusercontent.com/102282918/212053961-c54981be-ad7f-4fd1-adbb-e398d1f91c81.png)

”search_tumbnail_1” should be "search_thumbnail_1“.

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 
Test version : v1.0.3 released on 13th, Jan.

Due to exception error when upload photo, we cannot test.
Please Open this ticket again.

![image](https://user-images.githubusercontent.com/102282918/212591524-a3ea8209-eafe-4d84-8691-75df6f850b23.png)

[details.txt](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/files/10422250/details.txt)

**Comment by EricBourque** [comment]
May be related to DLL mismatch. Please re-install on Management Server and Smart Client and try again

**Comment by Yoshitaka-Fukushima** [comment]
Thank you. We confirmed This has been fixed.
