### ISSUE TITLE
When ”Search only within : Past month"  is used, not 30 days but 31 days is better to be used in API

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#67]
Test version : v1.0.2 released on 6th, Jan.

When this option is used, currently 30 days are specified in API. 

![image](https://user-images.githubusercontent.com/102282918/212210243-c8a2a3fe-c08b-4196-9786-21ca4d841493.png)

![image](https://user-images.githubusercontent.com/102282918/212210328-3d823bdc-6678-4f29-bf6b-07af48a42ecf.png)

Could you change to 31 days ? Our plug-in uses 31 days.
But if this change require complicated business logic, I want to keep 30 days to avoid risk.

**Comment by alexnaicuorbnet** [comment]
Change made.

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.0.3 released on 19th, Jan.
Fixed.
