### ISSUE TITLE
When multiple servers are used, deleting people watchlist failed in specific procedure

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#68]
Test version : v1.0.2 released on 6th on Jan.

Procedure
1. Register Active Guard server A and B (any server name is OK)

2 .Register people watchlist to Active Guard server A - > succeeded
3 .Register people watchlist to Active Guard server B - > succeeded
4. Edit watchlist registered in server A(No.3) and save.  - > succeeded.
5. Edit watchlist registered in server B(No.4) and save.  - > succeeded.
6. Delete the watchlist registered in  server A - > succeeded.
7. Delete the watchlist registered in  server B - > failed.
   *According to wireshark packet, request API in No.7 is sent to server A's IP Address. (API should be sent to server B)

**Comment by EricBourque** [comment]
Please test in version 1.0.3 release 24.01.2023
We are unable to reproduce with our current setup.

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 24th,Jan.

FIxed. (not reproduced in this version)
