### ISSUE TITLE
Exception error when clicking expand filter area button after closing it

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#69]
Test version: v1.0.3 released on 13th, Jan.

Procedure
1. Click button to close filter area (though it is difficult to see the button).
 
![image](https://user-images.githubusercontent.com/102282918/212658926-91738da9-5bfc-455d-9188-980092db1890.png)

2. Click button to expand
 
![image](https://user-images.githubusercontent.com/102282918/212658999-0a355c37-dbdb-4554-86d9-b9829e56609c.png)
 
Phenomenon
Exception error

 
![image](https://user-images.githubusercontent.com/102282918/212659078-0611fb8b-701c-4576-89b8-8010c8a68757.png)

Details

[Details.txt](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/files/10424959/Details.txt)

**Comment by alexnaicuorbnet** [comment]
Fixed.

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.0.3 released on 19th, Jan.
Fixed.
