### ISSUE TITLE
Icon image for Actions

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#7]
Sorry for late. I attach icon date for ["Actions"](

![image](https://user-images.githubusercontent.com/102282918/159913298-5caee530-8fed-4a30-a425-b55f1bdb9682.png)
![intruder](https://user-images.githubusercontent.com/102282918/159913442-9bf2a12d-d1d9-4c08-b587-a60355d4f2d1.png)
![face](https://user-images.githubusercontent.com/102282918/159913446-f324c773-30ec-4367-8308-4ae71bd9f302.png)
![saved_search](https://user-images.githubusercontent.com/102282918/159913451-6fcca0c9-0496-47f8-99b6-8b99818e155e.png)

**Comment by EricBourque** [comment]
No problem, thank you!
