### ISSUE TITLE
Initial filter for face and people are not correct when starting Smart Client in some PC

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#70]
Test version: v1.0.3 released on 13th, Jan.

When face and people application exist in the system and start Smart client, face and people filter are not shown correctly.

![image](https://user-images.githubusercontent.com/102282918/212671017-1aa9755d-d887-4b19-a961-ed7b7f01533d.png)

Expected
Face filter on/off button and people filter are shown.

Active Guard server respond correctly when starting Smart client.
![image](https://user-images.githubusercontent.com/102282918/212671311-e05f4978-2185-4182-85e6-eb4d2544d372.png)

When we create new tab, filter will be shown correctly.
So we assume that this is a problem that depends on the timing of processing at startup.

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 24.01.2023
When filters sections do not show instantly at startup they should show eventually (without creating new tab).

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 24th,Jan.
Fixed.
