### ISSUE TITLE
Improve message when the detected face size is under 75 pixel

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#73]
Test version : v1.0.3 released on 13th, Jan.

Currently ,when the detected size is under 75 pixel, "Detected width is not available." is shown, but actually this can be used for registration or search.

 Could you change to ""Detected width does not meet the recommended size." ?

![image](https://user-images.githubusercontent.com/102282918/213096274-969772b3-8c8c-4d14-95f1-93e403276761.png)

**Comment by alexnaicuorbnet** [comment]
As it is now, the message "Detected width is not available." is only shown when the "face_width" fields is 0 or empty/null.
![message](https://user-images.githubusercontent.com/115068792/213198299-3decd00a-f800-4da6-9cc3-7a3217a3d8b3.png)

When the field "face_width" is between 0 and 75 the following message is shown:

![message2](https://user-images.githubusercontent.com/115068792/213198567-68848dea-f0ad-4052-a2d4-ad8c25700fe7.png)
![message3](https://user-images.githubusercontent.com/115068792/213198591-674e892e-2020-4306-80da-7a345ab4a981.png)

**Comment by Yoshitaka-Fukushima** [comment]
Thank you. I think this is the issue on server side.

**Comment by Yoshitaka-Fukushima** [comment]
Currently, server responds "face_width" correctly for people search and always "zero" for face search.
It is not perfect, but it is the current specification.

So, could you change the message when "face_width" fields is 0 or empty/null ?

**Comment by alexnaicuorbnet** [comment]
Of course, changes made.

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.0.3 released on 19th, Jan.
not OK,

When registering face image, no message is shown.

![image](https://user-images.githubusercontent.com/102282918/213628455-c9e64445-fd7d-4640-9947-49553dfe746c.png)

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 23.01.2023

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.0.3 released on 24th, Jan.
not OK.

OK for face registration from people image

![image](https://user-images.githubusercontent.com/102282918/214747537-712c0899-88e9-4c7c-9d0c-411d4d70db1b.png)


Not OK for face registration from face image

Even if the size meet the recommended size, message is shown.
![image](https://user-images.githubusercontent.com/102282918/214747605-7d48a924-d502-44b1-95b6-048a18533a1c.png)
Sorry, if our requirement is not clear but this message should be shown when it does not meet the recommended size for face image.

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 27.01.2023
Now the check is made on the first item of "recommended_size", field "detect_pixel_width" ( < 75 to show the message). 
The field "recommended" : "yes"/"no" is not checked.  So if AG decides another limit for recommended width the smart client still checks for size 75.

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 27th,Jan
Fixed.

it is OK for following 4 cases
Face registration from face search which meet recommended size
Face registration from face search which does not meet recommended size
Face registration from people search which meet recommended size
Face registration from people search which does not meet recommended size
