### ISSUE TITLE
"First name" in face watchlist will be lost when changing Enable/Disable by right click menu

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#75]
Test version: v1.0.3 released on 13th, Jan.

Before operation
In this example ,First name is "FirstTest" and Last name is "LastTest".
 
![image](https://user-images.githubusercontent.com/102282918/213129724-43950842-17a4-4410-95f3-a02faee94ddb.png)

After clicking "Disable Matching" and load again,

(i)If "validity period" for the watchlist is disabled

![image](https://user-images.githubusercontent.com/102282918/213129984-f0e262dd-5f7d-44db-b85a-be2a462dac19.png)

First name does not exist.

According to wireshark packet, update API does not include "first_name".

![image](https://user-images.githubusercontent.com/102282918/213130192-f7f2ea3c-e429-458b-800d-44778104f213.png)

(ii)If "validity period" for the watchlist is enabled

![image](https://user-images.githubusercontent.com/102282918/213131807-05a97d84-3317-4e0d-b73c-dca4a9ef9876.png)

First name will be string like "Validity period".

![image](https://user-images.githubusercontent.com/102282918/213132020-5918071f-7ed6-4c2e-8383-b01fa50ed9fc.png)

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 20.01.2023

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 24th,Jan
Fixed
