### ISSUE TITLE
Face watchlist can be created without face image

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#76]
Test version: v1.0.3 released on 13th, Jan.

Setup watchlists- Face watchlists - New registration

Currently, face watchlist can be created without face image. (Actually this is no meaning as face watchlist).

![image](https://user-images.githubusercontent.com/102282918/213152349-935690c1-37d3-41ac-b161-34eabd2a45cf.png)

Could you disable or hide "Save" button when  no face picture is set ?

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 20.01.2023
Fixed by preventing saving with explanatory message.

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 24th,Jan
Fixed.
