### ISSUE TITLE
Cannot see all face watchlists when more than 10 watchilsts are registered.

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#77]
Test version v1.0.3 released on 13th, Jan.

Currently, not all watchlist can be shown even if windows is maximaized.

![image](https://user-images.githubusercontent.com/102282918/213327322-f9251418-486c-414e-9717-cea83ada9cb2.png)

![image](https://user-images.githubusercontent.com/102282918/213327433-7d2e4b78-0d89-44ff-81bf-8f4ea1d4f465.png)

Could you create a vertical scroll bar ?

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 20.01.2023
Added scroll view on face watchlist search (setup & filters).

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 24th,Jan
Fixed.
