### ISSUE TITLE
Exception error when saving with 5 or more images in face registration

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#78]
Test version :  v1.0.3 released on 13th, Jan.

Procedure
1. Open Setup watchlists- Face wathclists- New registration
2. Upload 5 or more face images
3. Save

Exception error
![image](https://user-images.githubusercontent.com/102282918/213337549-41486618-4e4c-4c85-928f-90f6db6c203f.png)

[3207_details.txt](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/files/10452748/3207_details.txt)

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 23.01.2023
This was fixed by increasing the waiting time for AG to return when saving, so a limit still exists.

**Comment by alexnaicuorbnet** [comment]
The increase is from 5s to 12s

**Comment by EricBourque** [comment]
Please test to see how many images you can upload now. We may need to increase this delay some more. This timeout is also used to detect when an Active Guard server goes offline so we should not increase the value too much.

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 24th,Jan

We repeatedly try to test and it takes around 10-13sec according to wireshark packet. So, sometimes error is shown.
Could you extend to 15 sec ?

![image](https://user-images.githubusercontent.com/102282918/214493045-04a8ffd4-26be-49ab-bb18-bf48f4f751a3.png)

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 25.01.2023
Increased to 15s.

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 27th, Jan.
Fixed.
