### ISSUE TITLE
Exception error when uploading gif image for face filter

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#79]
Test version : v1.0.3 released on 13th,Jan.

Exception error occurs when uploading gif image file for face filter.

[3213_details.txt](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/files/10453689/3213_details.txt)

I think this depends on OpenCV library, but gif file is no need as use case.

Currently
![image](https://user-images.githubusercontent.com/102282918/213361084-98c96a5d-5cb2-4d86-83af-06d54b6eb0db.png)

It seems all files are allowed for upload photo because "*.*" is included.

In case of Video Insight

![image](https://user-images.githubusercontent.com/102282918/213361223-fc102481-cf91-451e-b121-63df2c1e38c0.png)

Only bmp, jpeg, jpg and png are allowed.

I don't know if it's possible due to library differences, but can they be the same?

**Comment by EricBourque** [comment]
Update: We just need to stop users from Uploading GIF to remove the error

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.0.3 released on 19th, Jan.
Fixed.
