### ISSUE TITLE
Image in Face Registration must be cropped

### ISSUE THREAD

**Issue by EricBourque** [ORBNETSYS/i-PRO-Active-Guard-Public#8]

**Comment by Yoshitaka-Fukushima** [comment]
I want to explain detail. @EricBourque 

When face image is selected and click face registration button from Actions, face image is used without any cropping or modification. This is simple.
![fromfaceimg](https://user-images.githubusercontent.com/102282918/162653265-f3c5b797-084c-4f72-9345-a72bc140b8fa.JPG)


When people image is selected,

-Face registration button should be shown on GUI only when the image includes both face and upper body.

 Plugin can judge whether the image has face and upper body or not from API resoponse of  "/ai/v1.0/thumbnail/search/{search_session_id}"

![apiresponse_face_upper](https://user-images.githubusercontent.com/102282918/162653288-dc8727bf-52c6-4dee-bef1-bf1e6253f3dc.JPG)


-When face registration button is clicked,
  Upper body region should be cropped and used for face registration  using "upperbody_coordinate_x","upperbody_coordinate_y","upperbody_width" and "upperbody_height".
  
![frompeopleimg](https://user-images.githubusercontent.com/102282918/162653330-a5cad030-6ef0-4cfe-b3e4-c1d539c29472.JPG)

**Comment by EricBourque** [comment]
Should we also use face coordinates to crop or we only use upperbody coordinates?

**Comment by EricBourque** [comment]
Fixed for 0.9.4
