### ISSUE TITLE
Maximum number of characters in Face watchlist registration window

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#80]
Test version : v1.0.3 released on 13th, Jan.

Could you set an upper limit on the number of characters that can be entered ?

First Name：up to 50 characters
Last Name：up to 50 characters
Category：up to 20 characters
Remarks：up to 100 characters

This is from the design of our database considering encryption and error is shown if exceeded.

![image](https://user-images.githubusercontent.com/102282918/213367037-b13420bf-4178-40ac-aa70-04e4af520a7d.png)

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 20.01.2023
Added these limitations on several places.

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 24th,Jan
Fixed.
