### ISSUE TITLE
Face image in search API is not updated after uploading photo, searching, clear filter and upload another face 

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#81]
Test version: v1.0.3 released on 13th, Jan.

Procedure
1.Upload photo and search for face
2. Clear filter
3. Upload another photo and search for face

In the 2nd search, GUI shows the face for 2nd upload photo correctly, but API uses 1st face.

**Comment by EricBourque** [comment]
Please test in version 1.0.3 release 24.01.2023.
We tested ourselves, we noticed that two different base64 encoded images will start with the same prefix. Please compare the entire base64 string to see if the are different, the first few hundred characters may be the same.

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.0.3 released on 24th, Jan,
Fixed.

According to our test, 
we can reproduce in v1.0.3 released on 13th, Jan,
we cannot reproduce  in v1.0.3 released on 19th, Jan and v1.0.3 released on 24th, Jan.
