### ISSUE TITLE
「Multiple server registration]- Camera list in People watchlist registration window is always the list for 1st server

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#82]
Test version : v1.0.3 released on 13th, Jan.

Procedure
1. Register multiple i-PRO Active Guard server (two servers is enough)
    For example, 192.168.0.52 and 192.168.0.55 are registered to 1st server and others are 2nd server 
![image](https://user-images.githubusercontent.com/102282918/213601615-842d8375-6f56-4569-97bd-25b8c4d9ad20.png)

2. Open people watchlists window and change the server
3. Open camera list

![image](https://user-images.githubusercontent.com/102282918/213601729-f892ae84-df9f-46f1-ba06-6299eddd9f5a.png)

Currently,
camera with AI People detection in 1st server is always shown.

Expected
camera with AI People detection in the selected server is shown.

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 20.01.2023

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 24th,Jan
Fixed.
