### ISSUE TITLE
[Face search by upload photo]Face image is not included in API when client PC (Only smart client is installed) is used.

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#83]
Test version: v1.0.3 released on 19th,Jan.

Face searching by upload photo works well on the PC that Milestone server and Smart client is installed.

Face searching by upload photo does not work well on the PC that only Smart client is installed.
Face image data is not included in the API.

![image](https://user-images.githubusercontent.com/102282918/213681538-d6f14e62-1ffc-4879-80d1-b7fa0f120271.png)
 
Two of two PC has this issue. We use the same image for uploading photo.

We uninstalled plug-in, delete folder "C:\Program Files\Milestone\MIPPlugins\i-PRO\Active Guard” manually and installed again,
but situation did not change.

**Comment by EricBourque** [comment]
Please test in version 1.0.3 released 24.01.2023
Not able to reproduce. Please re-test again to see if it is resolved. If you prefer not to test again, please provide remote access so that we can debug on your system.

**Comment by Yoshitaka-Fukushima** [comment]
We tested more but could not reproduce this even if we use the original test version and do the same procedure.
We will close, and reopen if this phenomenon is occurred again.
