### ISSUE TITLE
[Upload photo] Maximum size 512x512 should be applied for not whole image but cropped face area

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#84]
Test version: v1.0.3 released on 24th, Jan.

When we upload photo which resolution is more than 512 x 512, error message is shown.

![image](https://user-images.githubusercontent.com/102282918/214745177-cbef3ead-224a-4f17-b1e1-ab523c60f7c3.png)

This maximum size should be applied not for whole image but each cropped face area.
Currently, this restriction causes much smaller face depending on the photo and result inaccurate search.

Based on previous discussion, currently, cropped face image includes 50% margin for left, right, top and bottom are added to the detected face by OpenCV as follows.

![face](https://user-images.githubusercontent.com/102282918/214746227-e75c7321-06e3-4c90-ab06-abafbf339646.png)

The maximum size case is as below and up to 256 pixel can be used detected by openCV (white rectangle).

![image](https://user-images.githubusercontent.com/102282918/214746619-f53a2c39-a940-44c1-8c66-587addd91e57.png)

**Comment by Yoshitaka-Fukushima** [comment]
There is typo in current message. "samller" is "smaller".

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 26.01.2023
Two restrictions still remain at upload time: file size <= 768kb and image size >=32*32

**Comment by Yoshitaka-Fukushima** [comment]
Thank you for comment. @alexnaicuorbnet 
Actually, limitation of file size( <= 768kb) and image size( >=32*32 ) are also not for whole image but cropped face region.

I think it is difficult to calculate the data size of cropped region. Is that correct ?
If so, could you remove the limitation about file size ?
In my experience, usually 512x512  jpeg file does not exceed 768kb.

**Comment by alexnaicuorbnet** [comment]
Thanks @Yoshitaka-Fukushima 
Does the minimum size 32*32 include the 50% margin?
As for the in-memory size of the cropped region -> I don't estimate it to take much effort.

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.3 on 26.01.2023
Removed the restrictions for file size and added the minimum 32*32 (including 50% border) and memory size under 768 KB for the detected faces cropped images that get sent to AG.

**Comment by Yoshitaka-Fukushima** [comment]
Thank you for implementation, it is OK. We will check. @alexnaicuorbnet

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.0.3 released on 27th,Jan.
Fixed.

**Comment by Yoshitaka-Fukushima** [comment]
I want to just confirm for our testing.

The feature to show message when detected face is under 75 pixel is not implemented for upload photo screen for search.
This has been implemented for face registration screen. Is it correct ?

**Comment by alexnaicuorbnet** [comment]
@Yoshitaka-Fukushima 
Indeed, that feature is not implemented at upload images for search, only at face registration.
Now in the upload images for search screen you are able to select images with size ranging from 32*32 (including 50% border) to 512*512 (including 50% border).

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
 I understand, current implementation is perfect.
I close this ticket.
