### ISSUE TITLE
Age range in face watchlist search window does not work

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#85]
Test version: v1.5.0 released on 30th,Jan

Age range field is not affected in the API.
![image](https://user-images.githubusercontent.com/102282918/215735548-35bd53f7-3caf-403b-83d4-5cc2d1fa3f99.png)

In this example,
{"op":"and","column":"age","comp":"range","min":"10","max":"30"} 
should be included.

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.0.5 on 31.01.2023

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v.1.5.0 released on 31th, Jan.
Not OK when only min age or max age is input on GUI.

(i)When only "min"(ex.10) is input,
currently
![image](https://user-images.githubusercontent.com/102282918/215933129-960858ca-eefc-4498-b969-705bf907b8fc.png)

Expected
{"op":"and","column":"age","comp":"range","min":"10"} exist.

(ii)When only "max"(ex.30) is input,

Expected
{"op":"and","column":"age","comp":"range","max":"30"} exist.

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.5.0 on 01.02.2023

**Comment by Yoshitaka-Fukushima** [comment]
Tested version: v1.5.0. on  01.02.2023.
Fixed.
