### ISSUE TITLE
When changing the Validity period on the People watchlist registration, the "Save" button is not displayed and cannot be updated

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#86]
Test version : v1.5.0 released on 30th,Jan.

When changing the Validity period on the People watchlist registration, the "Save" button is not displayed and cannot be updated.

![image](https://user-images.githubusercontent.com/102282918/215736730-4545fc99-8064-4788-ba02-0f66359b63c5.png)

**Comment by alexnaicuorbnet** [comment]
Issue fixed in version 1.5.0 on 31.01.2023

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.5.0 released on 31th,Jan.
Fixed.
