### ISSUE TITLE
Sometimes no camera can be selected. When starting plugin, plugin does not send API to get camera information.

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#9]
@EricBourque 
Test version: v0.9.3

According to wireshark packet, no request is sent from plugin.
On our side, we often encounter this phenomenon. 

By restarting Smart client, sometimes recovered.

If this is not occurred on your side, we want to provide any log file.

**Comment by EricBourque** [comment]
Have you tried with the hotfix?

**Comment by Yoshitaka-Fukushima** [comment]
Sorry for late, the phenomenon has been solved by using hotfix for XProtect Smart Client.

**Comment by EricBourque** [comment]
Fixed with Milestone cumulative patch installers for 2022R1
