### ISSUE TITLE
Two "PresetSettings.xml"  exist on client side

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#90]
Test version : v1.6.3

![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/8b760aed-3c75-4212-9cd6-fa176d0d1744)

Sorry if this is not bug, but two "PresetSettings.xml" exist on client PC.

@EricBourque  @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
The PresetSettings.xml file is the one used by the OSS. 
The PresetSettings - MilestonePC (Windows).xml file is the backup that is saved on the EventServer machine (it has user (usertype) in the name).
