### ISSUE TITLE
HTTPS connection is not avaialble

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#91]
Test version : v1.6.3

When HTTPS is used, "camera(0)" is shown. 
In case of sample app (direct communication with Active Guard server, HTTPS is no problem).
 
![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/5c0a5b71-b4e9-48a0-aa6c-c1d239b6a034)

@EricBourque  @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
I can't reproduce this yet
I've configured both the AG server and the Management Client for https 
![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/115068792/3c4663d3-20ef-4f01-b457-71de01131ca3)
![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/115068792/d26cae85-ff44-44df-a0aa-cf98f5454137)

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Could you upload screenshot that shows camera filter?

According to wireshark packet which HTTPs port is 8091, some communication is done at port 8091 correctly, but 8090 is also still used.

![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/d0fe9f70-bb54-4bb1-992f-c01c4dc51afd).

  I guess now this issue is similar to #92.

**Comment by alexnaicuorbnet** [comment]
Solved in v1.6.4 on 08.02.2024.

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.6.4
Fixed.
