### ISSUE TITLE
When Active Guard server's HTTP port is changed, "Camera(0)" is shown.

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#92]
Test version: v1.6.3

When Active Guard server HTTP port is change from 8090 (default) to other number(ex. 8093), "Camera (0)" is shown.

![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/45ae408c-6bad-4aa2-813b-0bb0b0dfd4da)

According to Wireshark packet between XProtect server(192.168.0.124) and  Active Guard server(192.168.0.122),
Two APIs /"ai/system/info" and "/ai/servers/info" are communicated at port 8093 correctly, but some API (we assume "ai/cameras/info" )tries to connect to 8090.

![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/9297311f-90f8-4eb5-8494-0b639cb55b9a)

@EricBourque  @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Solved in v1.6.4 on 08.02.2024.

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.6.4
Fixed.
