### ISSUE TITLE
License plate registration failed ( Hang-up when "Save" and finally failed )

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#93]
Test version : v1.6.3

Attached video ”TEST_20240206_185020.mp4” shows the overview.

Did you already implement LPR related API on Event server side?

https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/3285065d-d446-4171-9061-addde7086d53

@alexnaicuorbnet  @EricBourque

**Comment by alexnaicuorbnet** [comment]
Solved in v1.6.4 on 08.02.2024.

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.6.4
Fixed.
