### ISSUE TITLE
Smart client is aborted when switching tab during playback

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#95]
Test version: v1.6.3

Attached video files shows the overview.

https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/487e362d-2480-4f6d-99da-3d98724139c0

If there is limitation when switching tab, is there anyway to avoid this ?
ex. prohibit switching tab during playback or end playback automatically when switching tab.

@EricBourque  @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Fixed in 1.6.5 on 15.02.2024

**Comment by alexnaicuorbnet** [comment]
During the development changing between tabs with opened players inside the plugin was also problematic.

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Thank you for fixing.
Does "inside the plugin was also problematic." mean inside the our dll ?
(do you mean is it better for i-PRO to check dll behavior?)

**Comment by alexnaicuorbnet** [comment]
A, I meant between several "Thumbnail search" tabs (as a test scenario).

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
I see.
Is that also fixed in v1.6.5?

**Comment by EricBourque** [comment]
Hello, is this still an issue?

**Comment by Yoshitaka-Fukushima** [comment]
Test result for multiple Active Guard tabs using v1.6.5 is OK.
