### ISSUE TITLE
Support multiple languages on Smart client plug-in configuration menu

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#96]
Test version : v1.6.3

Is it technically possible to support multiple languages for these items ?

![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/46cb166a-6d47-4815-8f8f-b3339debf8be)

If possible, I will provide translated words soon.

@EricBourque  @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Most likely yes, I'll investigate.

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Thank you. I upload file including translated words in advance.

[translatedword.xlsx](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/files/14209108/translatedword.xlsx)

**Comment by alexnaicuorbnet** [comment]
Fixed in version 1.6.5 on 15.02.2024 (vietnamese was missing from the excel file)

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v1.6.5
