### ISSUE TITLE
Playback time on "Popup playback" (right click menu) is not correct

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#98]
Test version: v1.7.0

Phenomenon
As attached mp4 file, playback time is not correct.(It seems that not bestshot image timestamp but current PC time is used)

This happens at US customer site and Japan test PC. 
If you cannot reproduce, please change the PC timezone from UTC time in UK to others.

https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/c71a7172-6840-4122-ad12-c34acfd30fda

@EricBourque  @alexnaicuorbnet

**Comment by EricBourque** [comment]
Thanks for the video, we are going to fix this for you soon.

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 
Thank you. Could you check the e-mail that I sent you 15th May? In the e-mail, I sent the update OSS and want you to replace it.

Actually, we did not receive any reply from you more than 1 month, but did you sent us any e-mail?
One thing I'm very concerned about is that our company central email server may not be able to properly receive emails from your company for some reason.

**Comment by EricBourque** [comment]
Sorry! I have just replied. Please let me know if you have received.

**Comment by Yoshitaka-Fukushima** [comment]
Solved in newer version
