### ISSUE TITLE
Smart client configuration options

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#99]
Test version : v1.9.0 on XProtect 2024R1

Current implementation
![image](https://github.com/user-attachments/assets/9caa3b26-971d-44f7-a863-5c5936c48f27)

Expected
1.Event search configuration is no need. Please delete it
2.Please change default values for OCR code and Container code to be as follows

(OCR Code recognition)
Filter name : OCR
Code name OCR code
Thumbnail content : Entire image

(Container Code recognition)
Thumbnail content : Entire image

3. Selected options is not saved. 
ex, (i)Select Entire image, 
![{FF9FCF07-5B1A-446B-AE9E-778C01AFD99C}](https://github.com/user-attachments/assets/71d49ab2-a662-47cc-a773-071ac6270e51)
(ii)close configuration UI and open again. 
![{27A5BA22-39B2-4807-92A2-124718BFB2DB}](https://github.com/user-attachments/assets/634c3ad7-bf4c-439d-8783-88c33e75325b)

@EricBourque  @alexnaicuorbnet 

@EricBourque  @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Solved for v.1.9.1

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 

Test version : 1.9.1
Test result: Not OK

No value is selected for Thumbnail content.
![image](https://github.com/user-attachments/assets/c66424a1-2e9b-42cd-8161-2681814d15a4)

**Comment by alexnaicuorbnet** [comment]
Solved for v.1.9.2

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v1.9.2.
